[package]
name = "merge-ez"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.18"  
ratatui = "0.26"
crossterm = "0.27" 
serde_json = "1.0" 
reqwest = { version = "0.11", features = ["blocking", "json"] } 
